-- Inserts for TABLE: ABILITIES
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (1, 'stench', 'Has a 10% chance of making target Pok�mon flinch with each hit.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (2, 'drizzle', 'Summons rain that lasts indefinitely upon entering battle.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (3, 'speed-boost', 'Raises Speed one stage after each turn.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (4, 'battle-armor', 'Protects against critical hits.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (5, 'sturdy', 'Prevents being KOed from full HP, leaving 1 HP instead.  Protects against the one-hit KO moves regardless of HP.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (6, 'damp', 'Prevents self destruct, explosion, and aftermath from working while the Pok�mon is in battle.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (7, 'limber', 'Prevents paralysis.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (8, 'sand-veil', 'Increases evasion to 1.25� during a sandstorm.  Protects against sandstorm damage.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (9, 'static', 'Has a 30% chance of paralyzing attacking Pok�mon on contact.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (10, 'volt-absorb', 'Absorbs electric moves, healing for 1/4 max HP.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (11, 'water-absorb', 'Absorbs water moves, healing for 1/4 max HP.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (12, 'oblivious', 'Prevents infatuation and protects against captivate.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (13, 'cloud-nine', 'Negates all effects of weather, but does not prevent the weather itself.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (14, 'compound-eyes', 'Increases moves'' accuracy to 1.3�.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (15, 'insomnia', 'Prevents sleep.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (16, 'color-change', 'Changes type to match when hit by a damaging move.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (17, 'immunity', 'Prevents poison.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (18, 'flash-fire', 'Protects against fire moves.  Once one has been blocked, the Pok�mon''s own Fire moves inflict 1.5� damage until it leaves battle.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (19, 'shield-dust', 'Protects against incoming moves'' extra effects.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (20, 'own-tempo', 'Prevents confusion.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (21, 'suction-cups', 'Prevents being forced out of battle by other Pok�mon''s moves.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (22, 'intimidate', 'Lowers opponents'' Attack one stage upon entering battle.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (23, 'shadow-tag', 'Prevents opponents from fleeing or switching out.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (24, 'rough-skin', 'Damages attacking Pok�mon for 1/8 their max HP on contact.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (25, 'wonder-guard', 'Protects against damaging moves that are not super effective.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (26, 'levitate', 'Evades ground moves.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (27, 'effect-spore', 'Has a 30% chance of inflcting either paralysis, poison, or sleep on attacking Pok�mon on contact.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (28, 'synchronize', 'Copies burns, paralysis, and poison received onto the Pok�mon that inflicted them.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (29, 'clear-body', 'Prevents stats from being lowered by other Pok�mon.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (30, 'natural-cure', 'Cures any major status ailment upon switching out.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (31, 'lightning-rod', 'Redirects single-target electric moves to this Pok�mon where possible.  Absorbs Electric moves, raising Special Attack one stage.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (32, 'serene-grace', 'Doubles the chance of moves'' extra effects occurring.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (33, 'swift-swim', 'Doubles Speed during rain.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (34, 'chlorophyll', 'Doubles Speed during strong sunlight.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (35, 'illuminate', 'Doubles the wild encounter rate.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (36, 'trace', 'Copies an opponent''s ability upon entering battle.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (37, 'huge-power', 'Doubles Attack in battle.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (38, 'poison-point', 'Has a 30% chance of poisoning attacking Pok�mon on contact.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (39, 'inner-focus', 'Prevents flinching.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (40, 'magma-armor', 'Prevents freezing.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (41, 'water-veil', 'Prevents burns.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (42, 'magnet-pull', 'Prevents steel opponents from fleeing or switching out.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (43, 'soundproof', 'Protects against sound-based moves.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (44, 'rain-dish', 'Heals for 1/16 max HP after each turn during rain.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (45, 'sand-stream', 'Summons a sandstorm that lasts indefinitely upon entering battle.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (46, 'pressure', 'Increases the PP cost of moves targetting the Pok�mon by one.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (47, 'thick-fat', 'Halves damage from fire and ice moves.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (48, 'early-bird', 'Makes sleep pass twice as quickly.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (49, 'flame-body', 'Has a 30% chance of burning attacking Pok�mon on contact.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (50, 'run-away', 'Ensures success fleeing from wild battles.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (51, 'keen-eye', 'Prevents accuracy from being lowered.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (52, 'hyper-cutter', 'Prevents Attack from being lowered by other Pok�mon.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (53, 'pickup', 'Picks up other Pok�mon''s used and Flung held items.  May also pick up an item after battle.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (54, 'truant', 'Skips every second turn.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (55, 'hustle', 'Strengthens physical moves to inflict 1.5� damage, but decreases their accuracy to 0.8�.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (56, 'cute-charm', 'Has a 30% chance of infatuating attacking Pok�mon on contact.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (57, 'plus', 'Increases Special Attack to 1.5� when a friendly Pok�mon has plus or minus.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (58, 'minus', 'Increases Special Attack to 1.5� when a friendly Pok�mon has plus or minus.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (59, 'forecast', 'Changes castform''s type and form to match the weather.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (60, 'sticky-hold', 'Prevents a held item from being removed by other Pok�mon.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (61, 'shed-skin', 'Has a 33% chance of curing any major status ailment after each turn.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (62, 'guts', 'Increases Attack to 1.5� with a major status ailment.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (63, 'marvel-scale', 'Increases Defense to 1.5� with a major status ailment.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (64, 'liquid-ooze', 'Damages opponents using leeching moves for as much as they would heal.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (65, 'overgrow', 'Strengthens grass moves to inflict 1.5� damage at 1/3 max HP or less.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (66, 'blaze', 'Strengthens fire moves to inflict 1.5� damage at 1/3 max HP or less.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (67, 'torrent', 'Strengthens water moves to inflict 1.5� damage at 1/3 max HP or less.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (68, 'swarm', 'Strengthens bug moves to inflict 1.5� damage at 1/3 max HP or less.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (69, 'rock-head', 'Protects against recoil damage.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (70, 'drought', 'Summons strong sunlight that lasts indefinitely upon entering battle.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (71, 'arena-trap', 'Prevents opponents from fleeing or switching out.  Eluded by flying-types and Pok�mon in the air.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (72, 'vital-spirit', 'Prevents sleep.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (73, 'white-smoke', 'Prevents stats from being lowered by other Pok�mon.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (74, 'pure-power', 'Doubles Attack in battle.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (75, 'shell-armor', 'Protects against critical hits.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (76, 'air-lock', 'Negates all effects of weather, but does not prevent the weather itself.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (77, 'tangled-feet', 'Doubles evasion when confused.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (78, 'motor-drive', 'Absorbs electric moves, raising Speed one stage.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (79, 'rivalry', 'Increases damage inflicted to 1.25� against Pok�mon of the same gender, but decreases damage to 0.75� against the opposite gender.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (80, 'steadfast', 'Raises Speed one stage upon flinching.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (81, 'snow-cloak', 'Increases evasion to 1.25� during hail.  Protects against hail damage.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (82, 'gluttony', 'Makes the Pok�mon eat any held Berry triggered by low HP below 1/2 its max HP.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (83, 'anger-point', 'Raises Attack to the maximum of six stages upon receiving a critical hit.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (84, 'unburden', 'Doubles Speed upon using or losing a held item.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (85, 'heatproof', 'Halves damage from fire moves and burns.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (86, 'simple', 'Doubles the Pok�mon''s stat modifiers.  These doubled modifiers are still capped at -6 or 6 stages.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (87, 'dry-skin', 'Causes 1/8 max HP in damage each turn during strong sunlight, but heals for 1/8 max HP during rain.  Increases damage from fire moves to 1.25�, but absorbs water moves, healing for 1/4 max HP.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (88, 'download', 'Raises the attack stat corresponding to the opponents'' weaker defense one stage upon entering battle.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (89, 'iron-fist', 'Strengthens punch-based moves to 1.2� their power.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (90, 'poison-heal', 'Heals for 1/8 max HP after each turn when poisoned in place of damage.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (91, 'adaptability', 'Increases the same-type attack bonus from 1.5� to 2�.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (92, 'skill-link', 'Extends two-to-five-hit moves and triple kick to their full length every time.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (93, 'hydration', 'Cures any major status ailment after each turn during rain.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (94, 'solar-power', 'Increases Special Attack to 1.5� but costs 1/8 max HP after each turn during strong sunlight.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (95, 'quick-feet', 'Increases Speed to 1.5� with a major status ailment.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (96, 'normalize', 'Makes the Pok�mon''s moves all act normal-type.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (97, 'sniper', 'Strengthens critical hits to inflict 3� damage rather than 2�.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (98, 'magic-guard', 'Protects against damage not directly caused by a move.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (99, 'no-guard', 'Ensures all moves used by and against the Pok�mon hit.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (100, 'stall', 'Makes the Pok�mon move last within its move''s priority bracket.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (101, 'technician', 'Strengthens moves of 60 base power or less to 1.5� their power.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (102, 'leaf-guard', 'Protects against major status ailments during strong sunlight.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (103, 'klutz', 'Prevents the Pok�mon from using its held item in battle.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (104, 'mold-breaker', 'Bypasses targets'' abilities if they could hinder or prevent a move.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (105, 'super-luck', 'Raises moves'' critical hit rates one stage.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (106, 'aftermath', 'Damages the attacker for 1/4 its max HP when knocked out by a contact move.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (107, 'anticipation', 'Notifies all trainers upon entering battle if an opponent has a super-effective move, self destruct, explosion, or a one-hit KO move.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (108, 'forewarn', 'Reveals the opponents'' strongest move upon entering battle.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (109, 'unaware', 'Ignores other Pok�mon''s stat modifiers for damage and accuracy calculation.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (110, 'tinted-lens', 'Doubles damage inflicted with not-very-effective moves.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (111, 'filter', 'Decreases damage taken from super-effective moves by 1/4.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (112, 'slow-start', 'Halves Attack and Speed for five turns upon entering battle.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (113, 'scrappy', 'Lets the Pok�mon''s normal and fighting moves hit ghost Pok�mon.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (114, 'storm-drain', 'Redirects single-target water moves to this Pok�mon where possible.  Absorbs Water moves, raising Special Attack one stage.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (115, 'ice-body', 'Heals for 1/16 max HP after each turn during hail.  Protects against hail damage.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (116, 'solid-rock', 'Decreases damage taken from super-effective moves by 1/4.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (117, 'snow-warning', 'Summons hail that lasts indefinitely upon entering battle.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (118, 'honey-gather', 'The Pok�mon may pick up honey after battle.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (119, 'frisk', 'Reveals an opponent''s held item upon entering battle.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (120, 'reckless', 'Strengthens recoil moves to 1.2� their power.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (121, 'multitype', 'Changes arceus''s type and form to match its held Plate.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (122, 'flower-gift', 'Increases friendly Pok�mon''s Attack and Special Defense to 1.5� during strong sunlight.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (123, 'bad-dreams', 'Damages sleeping opponents for 1/8 their max HP after each turn.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (77, 'tangled-feet', 'Doubles evasion when confused.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (78, 'motor-drive', 'Absorbs electric moves, raising Speed one stage.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (79, 'rivalry', 'Increases damage inflicted to 1.25� against Pok�mon of the same gender, but decreases damage to 0.75� against the opposite gender.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (80, 'steadfast', 'Raises Speed one stage upon flinching.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (81, 'snow-cloak', 'Increases evasion to 1.25� during hail.  Protects against hail damage.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (82, 'gluttony', 'Makes the Pok�mon eat any held Berry triggered by low HP below 1/2 its max HP.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (83, 'anger-point', 'Raises Attack to the maximum of six stages upon receiving a critical hit.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (84, 'unburden', 'Doubles Speed upon using or losing a held item.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (85, 'heatproof', 'Halves damage from fire moves and burns.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (86, 'simple', 'Doubles the Pok�mon''s stat modifiers.  These doubled modifiers are still capped at -6 or 6 stages.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (87, 'dry-skin', 'Causes 1/8 max HP in damage each turn during strong sunlight, but heals for 1/8 max HP during rain.  Increases damage from fire moves to 1.25�, but absorbs water moves, healing for 1/4 max HP.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (88, 'download', 'Raises the attack stat corresponding to the opponents'' weaker defense one stage upon entering battle.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (89, 'iron-fist', 'Strengthens punch-based moves to 1.2� their power.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (90, 'poison-heal', 'Heals for 1/8 max HP after each turn when poisoned in place of damage.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (91, 'adaptability', 'Increases the same-type attack bonus from 1.5� to 2�.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (92, 'skill-link', 'Extends two-to-five-hit moves and triple kick to their full length every time.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (93, 'hydration', 'Cures any major status ailment after each turn during rain.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (94, 'solar-power', 'Increases Special Attack to 1.5� but costs 1/8 max HP after each turn during strong sunlight.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (95, 'quick-feet', 'Increases Speed to 1.5� with a major status ailment.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (96, 'normalize', 'Makes the Pok�mon''s moves all act normal-type.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (97, 'sniper', 'Strengthens critical hits to inflict 3� damage rather than 2�.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (98, 'magic-guard', 'Protects against damage not directly caused by a move.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (99, 'no-guard', 'Ensures all moves used by and against the Pok�mon hit.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (100, 'stall', 'Makes the Pok�mon move last within its move''s priority bracket.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (101, 'technician', 'Strengthens moves of 60 base power or less to 1.5� their power.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (102, 'leaf-guard', 'Protects against major status ailments during strong sunlight.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (103, 'klutz', 'Prevents the Pok�mon from using its held item in battle.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (104, 'mold-breaker', 'Bypasses targets'' abilities if they could hinder or prevent a move.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (105, 'super-luck', 'Raises moves'' critical hit rates one stage.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (106, 'aftermath', 'Damages the attacker for 1/4 its max HP when knocked out by a contact move.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (107, 'anticipation', 'Notifies all trainers upon entering battle if an opponent has a super-effective move, self destruct, explosion, or a one-hit KO move.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (108, 'forewarn', 'Reveals the opponents'' strongest move upon entering battle.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (109, 'unaware', 'Ignores other Pok�mon''s stat modifiers for damage and accuracy calculation.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (110, 'tinted-lens', 'Doubles damage inflicted with not-very-effective moves.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (111, 'filter', 'Decreases damage taken from super-effective moves by 1/4.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (112, 'slow-start', 'Halves Attack and Speed for five turns upon entering battle.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (113, 'scrappy', 'Lets the Pok�mon''s normal and fighting moves hit ghost Pok�mon.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (114, 'storm-drain', 'Redirects single-target water moves to this Pok�mon where possible.  Absorbs Water moves, raising Special Attack one stage.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (115, 'ice-body', 'Heals for 1/16 max HP after each turn during hail.  Protects against hail damage.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (116, 'solid-rock', 'Decreases damage taken from super-effective moves by 1/4.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (117, 'snow-warning', 'Summons hail that lasts indefinitely upon entering battle.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (118, 'honey-gather', 'The Pok�mon may pick up honey after battle.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (119, 'frisk', 'Reveals an opponent''s held item upon entering battle.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (120, 'reckless', 'Strengthens recoil moves to 1.2� their power.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (121, 'multitype', 'Changes arceus''s type and form to match its held Plate.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (122, 'flower-gift', 'Increases friendly Pok�mon''s Attack and Special Defense to 1.5� during strong sunlight.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (123, 'bad-dreams', 'Damages sleeping opponents for 1/8 their max HP after each turn.');

[Done] exited with code=0 in 12.918 seconds

[Running] python -u "c:\Portal\University of Washington Bothell\2023 - 2024\Summer 2024\CSS-497-Pokedex-App\pokedex.py"
-- Inserts for TABLE: ABILITIES
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (124, 'pickpocket', 'Steals attacking Pok�mon''s held items on contact.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (125, 'sheer-force', 'Strengthens moves with extra effects to 1.3� their power, but prevents their extra effects.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (126, 'contrary', 'Inverts stat changes.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (127, 'unnerve', 'Prevents opposing Pok�mon from eating held Berries.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (128, 'defiant', 'Raises Attack two stages upon having any stat lowered.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (129, 'defeatist', 'Halves Attack and Special Attack at 50% max HP or less.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (130, 'cursed-body', 'Has a 30% chance of Disabling any move that hits the Pok�mon.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (131, 'healer', 'Has a 30% chance of curing each adjacent ally of any major status ailment after each turn.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (132, 'friend-guard', 'Decreases all direct damage taken by friendly Pok�mon to 0.75�.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (133, 'weak-armor', 'Raises Speed and lowers Defense by one stage each upon being hit by a physical move.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (134, 'heavy-metal', 'Doubles the Pok�mon''s weight.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (135, 'light-metal', 'Halves the Pok�mon''s weight.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (136, 'multiscale', 'Halves damage taken from full HP.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (137, 'toxic-boost', 'Increases Attack to 1.5� when poisoned.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (138, 'flare-boost', 'Increases Special Attack to 1.5� when burned.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (139, 'harvest', 'Has a 50% chance of restoring a used Berry after each turn if the Pok�mon has held no items in the meantime.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (140, 'telepathy', 'Protects against friendly Pok�mon''s damaging moves.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (141, 'moody', 'Raises a random stat two stages and lowers another one stage after each turn.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (142, 'overcoat', 'Protects against damage from weather.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (143, 'poison-touch', 'Has a 30% chance of poisoning target Pok�mon upon contact.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (144, 'regenerator', 'Heals for 1/3 max HP upon switching out.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (145, 'big-pecks', 'Protects against Defense drops.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (146, 'sand-rush', 'Doubles Speed during a sandstorm.  Protects against sandstorm damage.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (147, 'wonder-skin', 'Lowers incoming non-damaging moves'' base accuracy to exactly 50%.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (148, 'analytic', 'Strengthens moves to 1.3� their power when moving last.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (149, 'illusion', 'Takes the appearance of the last conscious party Pok�mon upon being sent out until hit by a damaging move.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (150, 'imposter', 'Transforms upon entering battle.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (151, 'infiltrator', 'Bypasses light screen, reflect, and safeguard.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (152, 'mummy', 'Changes attacking Pok�mon''s abilities to Mummy on contact.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (153, 'moxie', 'Raises Attack one stage upon KOing a Pok�mon.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (154, 'justified', 'Raises Attack one stage upon taking damage from a dark move.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (155, 'rattled', 'Raises Speed one stage upon being hit by a dark, ghost, or bug move.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (156, 'magic-bounce', 'Reflects most non-damaging moves back at their user.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (157, 'sap-sipper', 'Absorbs grass moves, raising Attack one stage.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (158, 'prankster', 'Raises non-damaging moves'' priority by one stage.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (159, 'sand-force', 'Strengthens rock, ground, and steel moves to 1.3� their power during a sandstorm.  Protects against sandstorm damage.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (160, 'iron-barbs', 'Damages attacking Pok�mon for 1/8 their max HP on contact.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (161, 'zen-mode', 'Changes darmanitan''s form after each turn depending on its HP: Zen Mode below 50% max HP, and Standard Mode otherwise.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (162, 'victory-star', 'Increases moves'' accuracy to 1.1� for friendly Pok�mon.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (163, 'turboblaze', 'Bypasses targets'' abilities if they could hinder or prevent moves.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (164, 'teravolt', 'Bypasses targets'' abilities if they could hinder or prevent moves.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (10001, 'mountaineer', '');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (10002, 'wave-rider', '');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (10003, 'skater', '');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (10004, 'thrust', '');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (10005, 'perception', '');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (10006, 'parry', '');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (10007, 'instinct', '');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (10008, 'dodge', '');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (10009, 'jagged-edge', '');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (10010, 'frostbite', '');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (10011, 'tenacity', '');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (10012, 'pride', '');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (10013, 'deep-sleep', '');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (10014, 'power-nap', '');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (10015, 'spirit', '');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (10016, 'warm-blanket', '');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (10017, 'gulp', '');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (10018, 'herbivore', '');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (10019, 'sandpit', '');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (10020, 'hot-blooded', '');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (10021, 'medic', '');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (10022, 'life-force', '');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (10023, 'lunchbox', '');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (10024, 'nurse', '');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (10025, 'melee', '');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (10026, 'sponge', '');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (10027, 'bodyguard', '');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (10028, 'hero', '');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (10029, 'last-bastion', '');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (10030, 'stealth', '');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (10031, 'vanguard', '');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (10032, 'nomad', '');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (10033, 'sequence', '');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (10034, 'grass-cloak', '');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (10035, 'celebrate', '');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (10036, 'lullaby', '');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (10037, 'calming', '');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (10038, 'daze', '');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (10039, 'frighten', '');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (10040, 'interference', '');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (10041, 'mood-maker', '');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (10042, 'confidence', '');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (10043, 'fortune', '');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (10044, 'bonanza', '');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (10045, 'explode', '');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (10046, 'omnipotent', '');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (10047, 'share', '');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (10048, 'black-hole', '');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (10049, 'shadow-dash', '');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (10050, 'sprint', '');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (10051, 'disgust', '');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (10052, 'high-rise', '');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (10053, 'climber', '');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (10054, 'flame-boost', '');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (10055, 'aqua-boost', '');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (10056, 'run-up', '');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (10057, 'conqueror', '');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (10058, 'shackle', '');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (10059, 'decoy', '');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (10060, 'shield', '');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (165, 'aroma-veil', 'Protects allies against moves that affect their mental state.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (166, 'flower-veil', 'Protects friendly grass Pok�mon from having their stats lowered by other Pok�mon.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (167, 'cheek-pouch', 'Restores HP upon eating a Berry, in addition to the Berry''s effect.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (168, 'protean', 'Changes the bearer''s type to match each move it uses.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (169, 'fur-coat', 'Halves damage from physical attacks.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (170, 'magician', 'Steals the target''s held item when the bearer uses a damaging move.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (171, 'bulletproof', 'Protects against bullet, ball, and bomb-based moves.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (172, 'competitive', 'Raises Special Attack by two stages upon having any stat lowered.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (173, 'strong-jaw', 'Strengthens biting moves to 1.5� their power.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (174, 'refrigerate', 'Turns the bearer''s normal moves into ice moves and strengthens them to 1.3� their power.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (175, 'sweet-veil', 'Prevents friendly Pok�mon from sleeping.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (176, 'stance-change', 'Changes aegislash to Blade Forme before using a damaging move, or Shield Forme before using kings shield.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (177, 'gale-wings', 'Raises flying moves'' priority by one stage.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (178, 'mega-launcher', 'Strengthens aura and pulse moves to 1.5� their power.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (179, 'grass-pelt', 'Boosts Defense while grassy terrain is in effect.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (180, 'symbiosis', 'Passes the bearer''s held item to an ally when the ally uses up its item.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (181, 'tough-claws', 'Strengthens moves that make contact to 1.33� their power.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (182, 'pixilate', 'Turns the bearer''s normal moves into fairy moves and strengthens them to 1.3� their power.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (183, 'gooey', 'Lowers attacking Pok�mon''s Speed by one stage on contact.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (184, 'aerilate', 'Turns the bearer''s normal moves into flying moves and strengthens them to 1.3� their power.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (185, 'parental-bond', 'Lets the bearer hit twice with damaging moves.  The second hit has half power.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (186, 'dark-aura', 'Strengthens dark moves to 1.33� their power for all friendly and opposing Pok�mon.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (187, 'fairy-aura', 'Strengthens fairy moves to 1.33� their power for all friendly and opposing Pok�mon.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (188, 'aura-break', 'Makes dark aura and fairy aura weaken moves of their respective types.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (189, 'primordial-sea', 'Creates heavy rain, which has all the properties of Rain Dance, cannot be replaced, and causes damaging Fire moves to fail.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (190, 'desolate-land', 'Creates extremely harsh sunlight, which has all the properties of Sunny Day, cannot be replaced, and causes damaging Water moves to fail.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (191, 'delta-stream', 'Creates a mysterious air current, which cannot be replaced and causes moves to never be super effective against Flying Pok�mon.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (192, 'stamina', 'Raises this Pok�mon''s Defense by one stage when it takes damage from a move.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (193, 'wimp-out', 'This Pok�mon automatically switches out when its HP drops below half.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (194, 'emergency-exit', 'This Pok�mon automatically switches out when its HP drops below half.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (195, 'water-compaction', 'Raises this Pok�mon''s Defense by two stages when it''s hit by a Water move.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (196, 'merciless', 'This Pok�mon''s moves critical hit against poisoned targets.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (197, 'shields-down', 'Transforms this Minior between Core Form and Meteor Form.  Prevents major status ailments and drowsiness while in Meteor Form.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (198, 'stakeout', 'This Pok�mon''s moves have double power against Pok�mon that switched in this turn.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (199, 'water-bubble', 'Halves damage from Fire moves, doubles damage of Water moves, and prevents burns.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (200, 'steelworker', 'This Pok�mon''s Steel moves have 1.5� power.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (201, 'berserk', 'Raises this Pok�mon''s Special Attack by one stage every time its HP drops below half.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (202, 'slush-rush', 'During Hail, this Pok�mon has double Speed.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (203, 'long-reach', 'This Pok�mon''s moves do not make contact.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (204, 'liquid-voice', 'Sound-based moves become Water-type.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (205, 'triage', 'This Pok�mon''s healing moves have their priority increased by 3.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (206, 'galvanize', 'This Pok�mon''s Normal moves are Electric and have their power increased to 1.2�.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (207, 'surge-surfer', 'Doubles this Pok�mon''s Speed on Electric Terrain.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (208, 'schooling', 'Wishiwashi becomes Schooling Form when its HP is 25% or higher.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (209, 'disguise', 'Prevents the first instance of battle damage.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (210, 'battle-bond', 'Transforms this Pok�mon into Ash-Greninja after fainting an opponent.  Water Shuriken''s power is 20 and always hits three times.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (211, 'power-construct', 'Transforms 10% or 50% Zygarde into Complete Forme when its HP is below 50%.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (212, 'corrosion', 'This Pok�mon can inflict poison on Poison and Steel Pok�mon.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (213, 'comatose', 'This Pok�mon always  acts as though it were Asleep.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (214, 'queenly-majesty', 'Opposing Pok�mon cannot use priority attacks.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (215, 'innards-out', 'When this Pok�mon faints from an opponent''s move, that opponent takes damage equal to the HP this Pok�mon had remaining.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (216, 'dancer', 'Whenever another Pok�mon uses a dance move, this Pok�mon will use the same move immediately afterwards.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (217, 'battery', 'Ally Pok�mon''s moves have their power increased to 1.3�.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (218, 'fluffy', 'Damage from contact moves is halved.  Damage from Fire moves is doubled.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (219, 'dazzling', 'Opposing Pok�mon cannot use priority attacks.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (220, 'soul-heart', 'This Pok�mon''s Special Attack rises by one stage every time any Pok�mon faints.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (221, 'tangling-hair', 'When this Pok�mon takes regular damage from a contact move, the attacking Pok�mon''s Speed lowers by one stage.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (222, 'receiver', 'When an ally faints, this Pok�mon gains its Ability.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (223, 'power-of-alchemy', 'When an ally faints, this Pok�mon gains its Ability.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (224, 'beast-boost', 'Raises this Pok�mon''s highest stat by one stage when it faints another Pok�mon.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (225, 'rks-system', 'Changes this Pok�mon''s type to match its held Memory.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (226, 'electric-surge', 'When this Pok�mon enters battle, it changes the terrain to Electric Terrain.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (227, 'psychic-surge', 'When this Pok�mon enters battle, it changes the terrain to Psychic Terrain.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (228, 'misty-surge', 'When this Pok�mon enters battle, it changes the terrain to Misty Terrain.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (229, 'grassy-surge', 'When this Pok�mon enters battle, it changes the terrain to Grassy Terrain.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (230, 'full-metal-body', 'Other Pok�mon cannot lower this Pok�mon''s stats.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (231, 'shadow-shield', 'When this Pok�mon has full HP, regular damage from moves is halved.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (232, 'prism-armor', 'Reduces super-effective damage to 0.75�.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (233, 'neuroforce', 'Increases super-effective damage dealt to 1.25�.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (234, 'intrepid-sword', 'Boosts the Pok�mon�s Attack stat when the Pok�mon
enters a battle.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (235, 'dauntless-shield', 'Boosts the Pok�mon�s Defense stat when the Pok�mon
enters a battle.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (236, 'libero', 'Changes the Pok�mon�s type to the type of the
move it�s about to use.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (237, 'ball-fetch', 'If the Pok�mon is not holding an item, it will fetch
the Pok� Ball from the first failed throw
of the battle.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (238, 'cotton-down', 'When the Pok�mon is hit by an attack, it scatters
cotton fluff around and lowers the Speed stat of
all Pok�mon except itself.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (239, 'propeller-tail', 'Ignores the effects of opposing Pok�mon�s Abilities and
moves that draw in moves.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (240, 'mirror-armor', 'Bounces back only the stat-lowering effects that
the Pok�mon receives.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (241, 'gulp-missile', 'When the Pok�mon uses Surf or Dive, it will come back
with prey. When it takes damage, it will spit out the prey
to attack.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (242, 'stalwart', 'Ignores the effects of opposing Pok�mon�s Abilities and
moves that draw in moves.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (243, 'steam-engine', 'Boosts the Pok�mon�s Speed stat drastically if hit by a
Fire- or Water-type move.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (244, 'punk-rock', 'Boosts the power of sound-based moves.
The Pok�mon also takes half the damage from
these kinds of moves.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (245, 'sand-spit', 'The Pok�mon creates a sandstorm when it�s hit by
an attack.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (246, 'ice-scales', 'The Pok�mon is protected by ice scales, which halve
the damage taken from special moves.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (247, 'ripen', 'Ripens Berries and doubles their effect.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (248, 'ice-face', 'The Pok�mon�s ice head can take a physical attack as
a substitute, but the attack also changes the Pok�mon�s
appearance. The ice will be restored when it hails.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (249, 'power-spot', 'Just being next to the Pok�mon powers up moves.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (250, 'mimicry', 'Changes the Pok�mon�s type depending on the terrain.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (251, 'screen-cleaner', 'When the Pok�mon enters a battle, the effects of
Light Screen, Reflect, and Aurora Veil are nullified for
both opposing and ally Pok�mon.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (252, 'steely-spirit', 'Powers up ally Pok�mon�s Steel-type moves.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (253, 'perish-body', 'When hit by a move that makes direct contact,
the Pok�mon and the attacker will faint after three turns
unless they switch out of battle.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (254, 'wandering-spirit', 'The Pok�mon exchanges Abilities with a Pok�mon
that hits it with a move that makes direct contact.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (255, 'gorilla-tactics', 'Boosts the Pok�mon�s Attack stat but only allows
the use of the first selected move.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (256, 'neutralizing-gas', 'If the Pok�mon with Neutralizing Gas is in the battle,
the effects of all Pok�mon�s Abilities will be nullified
or will not be triggered.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (257, 'pastel-veil', 'Protects the Pok�mon and its ally Pok�mon from
being poisoned.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (258, 'hunger-switch', 'The Pok�mon changes its form, alternating between
its Full Belly Mode and Hangry Mode after the end of
each turn.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (259, 'quick-draw', 'Enables the Pok�mon to move first occasionally.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (260, 'unseen-fist', 'If the Pok�mon uses moves that make direct contact,
it can attack the target even if the target protects itself.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (261, 'curious-medicine', 'When the Pok�mon enters a battle, it scatters medicine
from its shell, which removes all stat changes
from allies.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (262, 'transistor', 'Powers up Electric-type moves.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (263, 'dragons-maw', 'Powers up Dragon-type moves.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (264, 'chilling-neigh', 'When the Pok�mon knocks out a target, it utters a
chilling neigh, which boosts its Attack stat.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (265, 'grim-neigh', 'When the Pok�mon knocks out a target, it utters a
terrifying neigh, which boosts its Sp. Atk stat.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (266, 'as-one-glastrier', 'This Ability combines the effects of both Calyrex�s
Unnerve Ability and Glastrier�s Chilling Neigh Ability.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (267, 'as-one-spectrier', 'This Ability combines the effects of both Calyrex�s
Unnerve Ability and Spectrier�s Grim Neigh Ability.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (268, 'lingering-aroma', 'Contact with the Pok�mon changes the attacker''s Ability to Lingering Aroma.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (269, 'seed-sower', 'Turns the ground into Grassy Terrain when the Pok�mon is hit by an attack.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (270, 'thermal-exchange', 'Boosts the Attack stat when the Pok�mon is hit by a Fire-type move. The Pok�mon also cannot be burned.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (271, 'anger-shell', 'When an attack causes its HP to drop to half or less, the Pok�mon gets angry. This lowers its Defense and Sp. Def stats but boosts its Attack, Sp. Atk, and Speed stats.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (272, 'purifying-salt', 'The Pok�mon''s pure salt protects it from status conditions and halves the damage taken from Ghost-type moves.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (273, 'well-baked-body', 'The Pok�mon takes no damage when hit by Fire-type moves. Instead, its Defense stat is sharply boosted.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (274, 'wind-rider', 'Boosts the Pok�mon''s Attack stat if Tailwind takes effect or if the Pok�mon is hit by a wind move. The Pok�mon also takes no damage from wind moves.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (275, 'guard-dog', 'Boosts the Pok�mon�s Attack stat if intimidated. Moves and items that would force the Pok�mon to switch out also fail to work.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (276, 'rocky-payload', 'Powers up Rock-type moves.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (277, 'wind-power', 'The Pok�mon becomes charged when it is hit by a wind move, boosting the power of the next Electric-type move the Pok�mon uses.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (278, 'zero-to-hero', 'The Pok�mon transforms into its Hero Form when it switches out.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (279, 'commander', 'When the Pok�mon enters a battle, it goes inside the mouth of an ally Dondozo if one is on the field. The Pok�mon then issues commands from there.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (280, 'electromorphosis', 'The Pok�mon becomes charged when it takes damage, boosting the power of the next Electric-type move the Pok�mon uses.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (281, 'protosynthesis', 'Boosts the Pok�mon''s most proficient stat in harsh sunlight or if the Pok�mon is holding Booster Energy.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (282, 'quark-drive', 'Boosts the Pok�mon''s most proficient stat on Electric Terrain or if the Pok�mon is holding Booster Energy.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (283, 'good-as-gold', 'A body of pure, solid gold gives the Pok�mon full immunity to other Pok�mon''s status moves.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (284, 'vessel-of-ruin', 'The power of the Pok�mon''s ruinous vessel lowers the Sp. Atk stats of all Pok�mon except itself.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (285, 'sword-of-ruin', 'The power of the Pok�mon''s ruinous sword lowers the Defense stats of all Pok�mon except itself.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (286, 'tablets-of-ruin', 'The power of the Pok�mon''s ruinous wooden tablets lowers the Attack stats of all Pok�mon except itself.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (287, 'beads-of-ruin', 'The power of the Pok�mon''s ruinous beads lowers the Sp. Def stats of all Pok�mon except itself.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (288, 'orichalcum-pulse', 'Turns the sunlight harsh when the Pok�mon enters a battle. The ancient pulse thrumming through the Pok�mon also boosts its Attack stat in harsh sunlight.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (289, 'hadron-engine', 'Turns the ground into Electric Terrain when the Pok�mon enters a battle. The futuristic engine within the Pok�mon also boosts its Sp. Atk stat on Electric Terrain.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (290, 'opportunist', 'If an opponent''s stat is boosted, the Pok�mon seizes the opportunity to boost the same stat for itself.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (291, 'cud-chew', 'When the Pok�mon eats a Berry, it will regurgitate that Berry at the end of the next turn and eat it one more time.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (292, 'sharpness', 'Powers up slicing moves.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (293, 'supreme-overlord', 'When the Pok�mon enters a battle, its Attack and Sp. Atk stats are slightly boosted for each of the allies in its party that have already been defeated.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (294, 'costar', 'When the Pok�mon enters a battle, it copies an ally''s stat changes.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (295, 'toxic-debris', 'Scatters poison spikes at the feet of the opposing team when the Pok�mon takes damage from physical moves.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (296, 'armor-tail', 'The mysterious tail covering the Pok�mon''s head makes opponents unable to use priority moves against the Pok�mon or its allies.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (297, 'earth-eater', 'If hit by a Ground-type move, the Pok�mon has its HP restored instead of taking damage.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (298, 'mycelium-might', 'The Pok�mon will always act more slowly when using status moves, but these moves will be unimpeded by the Ability of the target.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (299, 'minds-eye', 'The Pok�mon ignores changes to opponents'' evasiveness, its accuracy can''t be lowered, and it can hit Ghost types with Normal-type and Fighting-type moves');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (300, 'supersweet-syrup', 'Lowers the evasion of opposing Pok�mon by 1 stage when first sent into battle');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (301, 'hospitality', 'When the Pok�mon enters a battle, it showers its ally with hospitality, restoring a small amount of the ally''s HP');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (302, 'toxic-chain', 'The power of the Pok�mon''s toxic chain may badly poison any target the Pok�mon hits with a move');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (303, 'embody-aspect', 'The Pok�mon''s heart fills with memories, causing the Mask to shine and one of the Pok�mon''s stats to be boosted.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (304, 'tera-shift', 'When the Pok�mon enters a battle, it absorbs the energy around itself and transforms into its Terastal Form.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (305, 'tera-shell', 'The Pok�mon''s shell contains the powers of each type. All damage-dealing moves that hit the Pok�mon when its HP is full will not be very effective.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (306, 'teraform-zero', 'When Terapagos changes into its Stellar Form, it uses its hidden powers to eliminate all effects of weather and terrain, reducing them to zero.');
INSERT INTO ABILITIES (abi_id, abi_name, abi_desc) VALUES (307, 'poison-puppeteer', 'Pok�mon poisoned by Pecharunt''s moves will also become confused.');
