name: pokedex_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.3
  sqflite: ^2.3.3+1
  path: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/pokedex.db
    - assets/icons/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/pokedex_icon.png"
  # use "flutter pub run flutter_launcher_icons:main" to generate new icons
